version: '1.0.{build}'

platform:
  - x86
configuration:
  - Release

environment:
  matrix:
    - PYTHON: "C:\\Python35"


before_build:
  - "dir"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe deploy_scripts/set_app_version_during_ci.py %APPVEYOR_REPO_TAG_NAME%"

build_script:
  - "%PYTHON%\\python.exe cx_setup.py build"

after_build:
  - "7z a kaira-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\\build\\exe.win32-3.5"

artifacts:
  - path: "kaira-%APPVEYOR_BUILD_VERSION%.zip"
    name: Kaira

deploy:
  - provider: GitHub
    artifact: /.*\.zip/           # upload all zip files
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true # deploy on tag push only
    description: "Appveyor automatic CI build. Please install by copying contents of the zip file into base install folder."
    auth_token:
      secure: dVhUugZ838SU7EjJOeQRNhX/PFvsx9cnsERrZhzLZXkwnmNbP/iKywebkrrFTAzd

