version: '1.0.{build}'

platform:
  - x86
configuration:
  - Release

environment:
  matrix:
    - PYTHON: "C:\\Python35"

before_build:
  - "dir"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "echo v%APPVEYOR_BUILD_VERSION%"
  - "%PYTHON%\\python.exe deploy_scripts/set_app_version_during_ci.py v%APPVEYOR_BUILD_VERSION%"

build_script:
  - "%PYTHON%\\python.exe cx_setup.py build"

after_build:
  - "7z a kaira-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\\build\\exe.win32-3.5"

artifacts:
  - path: "kaira-%APPVEYOR_BUILD_VERSION%.zip"
    name: Kaira

skip_tags: true

deploy:
  - provider: GitHub
    release: v$(appveyor_build_version)
    artifact: /.*\.zip/           # upload all zip files
    draft: false
    prerelease: false
    on:
      branch: master # deploy on push to master
    description: "Appveyor automatic build. Please install by copying contents of the zip file into base install folder.\n\n$(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n$(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)"
    auth_token:
      secure: dVhUugZ838SU7EjJOeQRNhX/PFvsx9cnsERrZhzLZXkwnmNbP/iKywebkrrFTAzd

